global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bidmart-auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # host.docker.internal = Spring Boot running via ./gradlew bootRun on host machine
      - targets: ['host.docker.internal:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'bidmart-auth-service'
